version: '3'

services:
  nginx:
    image: nginx
    ports:
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/server.crt:/etc/nginx/certs/server.crt
      - ./nginx/server.key:/etc/nginx/certs/server.key
      - ./web/dst:/var/www/html
