AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Parameters:
  FileApiCustomDomain:
    Type: String
  ApiCustomDomain:
    Type: String
  StaticPageDomain:
    Type: String
  StaticPageBucket:
    Type: String
  CertificateArn:
    Type: String
  ApiStageName:
    Type: String
  AllowOrigin:
    Type: String
  WhiteIpAddressFrom:
    Type: String
  WhiteIpAddressTo:
    Type: String
  DbSuffix:
    Type: String
  LambdaMemorySize:
    Type: String
  FileStorageBucketSuffix:
    Type: String
  MyLayer:
    Type: String
  FileAPIName:
    Type: String
  Route53HostZone:
    Type: String
  RoleArn:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    CodeUri: app/
    Environment:
      Variables:
        AllowOrigin: !Ref AllowOrigin
        DbSuffix: !Ref DbSuffix
        FileStorageBucketSuffix: !Ref FileStorageBucketSuffix
        EnvName: !Ref ApiStageName
    MemorySize: 1024
    Layers: 
      - !Ref MyLayer
    Runtime: python3.8
    Timeout: 5

Resources:
  RestFileApi:
    Type: AWS::Serverless::Api
    Properties:
      BinaryMediaTypes:
        - "*/*"
      EndpointConfiguration: REGIONAL
      Cors:
        AllowCredentials: true
        AllowHeaders: "'Origin, Authorization, Accept, Content-Type'"
        AllowMethods: "'GET, PUT, POST, OPTIONS'"
        AllowOrigin: !Ref AllowOrigin
      Domain:
        DomainName: !Ref FileApiCustomDomain
        CertificateArn: !Ref CertificateArn
        Route53:
          HostedZoneId: !Ref Route53HostZone
        SecurityPolicy: TLS_1_2
      Name: !Ref FileAPIName
      StageName: !Ref ApiStageName
  
  GetFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: files.get_file_event
      Role: !Ref RoleArn
      Events:
        DefaultEvent:
          Type: Api
          Properties:
            RestApiId: !Ref RestFileApi
            Path: /get_file
            Method: get

# Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldApi:
  #   Description: "API Gateway endpoint URL for Stg stage for Hello World function"
  #   Value: !Sub "https://${ApiCustomDomain}/Stage/hello/"

