version = 0.1
[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "md-memo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1azphhnlpwj0y"
s3_prefix = "md-memo"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[develop]
[develop.deploy]
[develop.deploy.parameters]
stack_name = "md-memo-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1azphhnlpwj0y"
s3_prefix = "md-memo-dev"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"dev\""
