version = 0.1
[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "md-memo-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1azphhnlpwj0y"
s3_prefix = "md-memo-prod"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"prod\""

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "md-memo-stg"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1azphhnlpwj0y"
s3_prefix = "md-memo-stg"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"stg\""

[develop]
[develop.deploy]
[develop.deploy.parameters]
stack_name = "md-memo-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1azphhnlpwj0y"
s3_prefix = "md-memo-dev"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"dev\""

[local]
[local.deploy]
[local.deploy.parameters]
stack_name = "md-memo-local"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1azphhnlpwj0y"
s3_prefix = "md-memo-dev"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"local\""
