AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Parameters:
  Env:
    Type: String
    AllowedValues:
      - prod
      - stg
      - dev
      - local
    Default: local

Mappings:
  EnvMap:
    prod:
      FileApiCustomDomain: 'fileapi.memo-ease.com'
      ApiCustomDomain: 'api.memo-ease.com'
      StaticPageDomain: 'memo-ease.com'
      StaticPageBucket: 'md-memo-staticpage-prod'
      CertificateArn: 'arn:aws:acm:ap-northeast-1:913905735063:certificate/8758016f-7700-4566-b6bb-53ffdbf6c503'
      ApiStageName: 'Prod'
      AllowOrigin: "'https://memo-ease.com'"
      WhiteIpAddressFrom: '0.0.0.0'
      WhiteIpAddressTo: '255.255.255.255'
      APIName: 'MD Memo API Production'
      FileAPIName: 'MD Memo File API Production'
      DbSuffix: '_prod'
      LambdaMemorySize: 1024
      FileStorageBucketSuffix: '-prod'
      Route53HostZone: 'Z08559892LNONYYLAEN9Q'
    stg:
      FileApiCustomDomain: 'fileapi.stg-md-memo.tori-blog.net'
      ApiCustomDomain: 'api.stg-md-memo.tori-blog.net'
      StaticPageDomain: "'stg-md-memo.tori-blog.net'"
      StaticPageBucket: 'md-memo-staticpage-stg'
      CertificateArn: 'arn:aws:acm:ap-northeast-1:913905735063:certificate/0b1dc21b-3546-491d-8802-4d22af2e66a2'
      ApiStageName: 'Stg'
      AllowOrigin: "'https://stg-md-memo.tori-blog.net'"
      WhiteIpAddressFrom: '14.10.121.32'
      WhiteIpAddressTo: '14.10.121.32'
      APIName: 'MD Memo API staging'
      FileAPIName: 'MD Memo File API staging'
      DbSuffix: '_stg'
      LambdaMemorySize: 512
      FileStorageBucketSuffix: '-stg'
      Route53HostZone: 'Z2JCR6TK8NIB6U'
    dev:
      FileApiCustomDomain: 'fileapi.dev-md-memo.tori-blog.net'
      ApiCustomDomain: 'api.dev-md-memo.tori-blog.net'
      StaticPageDomain: "'dev-md-memo.tori-blog.net'"
      StaticPageBucket: 'md-memo-staticpage-dev'
      CertificateArn: 'arn:aws:acm:ap-northeast-1:913905735063:certificate/28036895-d230-4d61-9103-ac98781d8a04'
      ApiStageName: 'Dev'
      AllowOrigin: "'https://dev-md-memo.tori-blog.net'"
      WhiteIpAddressFrom: '14.10.121.32'
      WhiteIpAddressTo: '14.10.121.32'
      APIName: 'MD Memo API develop'
      FileAPIName: 'MD Memo File API develop'
      DbSuffix: '_dev'
      LambdaMemorySize: 512
      FileStorageBucketSuffix: '-dev'
      Route53HostZone: 'Z2JCR6TK8NIB6U'
    local:
      FileApiCustomDomain: 'localfileapi.dev-md-memo.tori-blog.net'
      ApiCustomDomain: 'localapi.dev-md-memo.tori-blog.net'
      StaticPageDomain: "'dev-md-memo.tori-blog.net'"
      StaticPageBucket: 'md-memo-staticpage-dev'
      CertificateArn: 'arn:aws:acm:ap-northeast-1:913905735063:certificate/28036895-d230-4d61-9103-ac98781d8a04'
      ApiStageName: 'Local'
      AllowOrigin: "'https://dev-md-memo.tori-blog.net'"
      WhiteIpAddressFrom: '0.0.0.0'
      WhiteIpAddressTo: '255.255.255.255'
      APIName: 'MD Memo API develop'
      FileAPIName: 'MD Memo File API develop'
      DbSuffix: '_dev'
      LambdaMemorySize: 512
      FileStorageBucketSuffix: '-dev'
      Route53HostZone: 'Z2JCR6TK8NIB6U'

Resources:
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Layer description
      ContentUri: 'my_layer_libs/'
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8

  MyApi1:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./api_template.yaml
      Parameters:
        FileApiCustomDomain: !FindInMap [EnvMap, !Ref Env, FileApiCustomDomain]
        ApiCustomDomain: !FindInMap [EnvMap, !Ref Env, ApiCustomDomain]
        StaticPageDomain: !FindInMap [EnvMap, !Ref Env, StaticPageDomain]
        StaticPageBucket: !FindInMap [EnvMap, !Ref Env, StaticPageBucket]
        CertificateArn: !FindInMap [EnvMap, !Ref Env, CertificateArn]
        ApiStageName: !FindInMap [EnvMap, !Ref Env, ApiStageName]
        AllowOrigin: !FindInMap [EnvMap, !Ref Env, AllowOrigin]
        WhiteIpAddressFrom: !FindInMap [EnvMap, !Ref Env, WhiteIpAddressFrom]
        WhiteIpAddressTo: !FindInMap [EnvMap, !Ref Env, WhiteIpAddressTo]
        DbSuffix: !FindInMap [EnvMap, !Ref Env, DbSuffix]
        LambdaMemorySize: !FindInMap [EnvMap, !Ref Env, LambdaMemorySize]
        FileStorageBucketSuffix: !FindInMap [EnvMap, !Ref Env, FileStorageBucketSuffix]
        MyLayer: !Ref MyLayer
        APIName: !FindInMap [EnvMap, !Ref Env, APIName]
        Route53HostZone: !FindInMap [EnvMap, !Ref Env, Route53HostZone]
  
  MyApi2:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./file_api_template.yaml
      Parameters:
        FileApiCustomDomain: !FindInMap [EnvMap, !Ref Env, FileApiCustomDomain]
        ApiCustomDomain: !FindInMap [EnvMap, !Ref Env, ApiCustomDomain]
        StaticPageDomain: !FindInMap [EnvMap, !Ref Env, StaticPageDomain]
        StaticPageBucket: !FindInMap [EnvMap, !Ref Env, StaticPageBucket]
        CertificateArn: !FindInMap [EnvMap, !Ref Env, CertificateArn]
        ApiStageName: !FindInMap [EnvMap, !Ref Env, ApiStageName]
        AllowOrigin: !FindInMap [EnvMap, !Ref Env, AllowOrigin]
        WhiteIpAddressFrom: !FindInMap [EnvMap, !Ref Env, WhiteIpAddressFrom]
        WhiteIpAddressTo: !FindInMap [EnvMap, !Ref Env, WhiteIpAddressTo]
        DbSuffix: !FindInMap [EnvMap, !Ref Env, DbSuffix]
        LambdaMemorySize: !FindInMap [EnvMap, !Ref Env, LambdaMemorySize]
        FileStorageBucketSuffix: !FindInMap [EnvMap, !Ref Env, FileStorageBucketSuffix]
        MyLayer: !Ref MyLayer
        FileAPIName: !FindInMap [EnvMap, !Ref Env, FileAPIName]
        Route53HostZone: !FindInMap [EnvMap, !Ref Env, Route53HostZone]
