# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the staging branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    name: Build And Upload to S3
    runs-on: ubuntu-latest

    steps:
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - uses: r0zar/sam-deploy-action@v1.4
        env:
          TEMPLATE: 'lambda/template.yaml'
          AWS_STACK_NAME: md-memo-prod
          AWS_REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEPLOY_BUCKET: md-memo-lambda-deploy
          PARAMETER_OVERRIDES:
            - Env=prod
      - name: Sync s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PROD_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: 'ap-northeast-1'   # S3のリージョンを指定します
          SOURCE_DIR: 'web'      # S3のデプロイ対象のディレクトリを指定します  
