# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the staging branch
  push:
    branches: [ staging ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    name: Build And Upload to S3
    runs-on: ubuntu-latest

    steps:
    - name: S3 Sync
    # You may pin to the exact commit or the version.
    # uses: jakejarvis/s3-sync-action@be0c4ab89158cac4278689ebedd8407dd5f35a83
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        AWS_ACCESS_KEY_ID_S3: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY_S3: ${{ secrets.AWS_SECRET_KEY }}
        AWS_S3_BUCKET: 'md-memo-stg'
        AWS_DEFAULT_REGION_S3: ap-northeast-1
